# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jerrynim-blog-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerrynim-blog-server
  template:
    metadata:
      labels:
        app: jerrynim-blog-server
    spec:
      containers:
        - name: jerrynim-blog-server-container
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/$GCLOUD_PROJECT/jerrynim-blog-server:latest
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
